theme: cayman
title: SemEval 2024: The Legal Argument Reasoning Task in Civil Procedure
description: The official page for the SemEval 2024 task on the Legal Argument Reasoning Task in Civil Procedure
